version: '3'

services:
  apache:
    image: apache-httpd
    ports: 
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
    depends_on:
      - php
      - mysql
    restart: unless-stopped
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  php:
    image: php:7.2.7-fpm-alpine3.7
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: docker_database
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8000:80'
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend: